<template>
  <AppLayout>
    <div class="studio-page registry-page">
      <section class="registry-guide"><strong>자산 등록 절차</strong><ol><li v-for="(item,index) in steps" :key="item.title"><b>0{{ index+1 }}</b><div><strong>{{ item.title }}</strong><span>{{ item.short }}</span></div><ArrowRight v-if="index<3" :size="17" /></li></ol></section>

      <section class="registry-history"><header><div><span>MY ASSETS</span><h2>나의 AI 자산 등록 기록</h2><p>제출한 자산의 심사 상태를 확인할 수 있습니다.</p></div><b>{{ myAssets.length }}건</b></header><div v-if="historyLoading" class="content-state"><LoaderCircle class="spin" />등록 기록을 불러오는 중입니다.</div><div v-else-if="myAssets.length" class="registry-history-list"><article v-for="asset in myAssets" :key="asset.asset_id"><span><Bot :size="18" /></span><div><strong>{{ asset.asset_name }}</strong><small>{{ asset.business_area }} · {{ asset.maturity_level }}</small></div><time>{{ date(asset.created_at) }}</time><nav><button @click="viewDocument(asset)"><Eye :size="13" />View</button><button v-if="['approved','rejected'].includes(asset.approval_status)" @click="feedback=asset"><MessageSquareText :size="13" />심사평</button></nav><em :class="asset.approval_status">{{ statusLabel(asset.approval_status) }}</em></article></div><div v-else class="content-state empty"><ShieldCheck :size="28" /><strong>아직 제출한 AI 자산이 없습니다.</strong><span>등록을 완료하면 심사 상태가 여기에 표시됩니다.</span></div></section>

      <nav v-if="!submitted" class="registry-stepper"><template v-for="(item,index) in steps" :key="item.title"><button :class="{active:step===index,done:maxStep>index}" :disabled="index>maxStep" @click="step=index"><span>{{ maxStep>index?'✓':index+1 }}</span><strong>{{ item.title }}</strong></button><i v-if="index<3"></i></template></nav>

      <section v-if="submitted" class="registry-complete"><span><CheckCircle2 :size="30" /></span><h2>제출이 완료되었습니다</h2><p>AI 자산 등록 요청이 접수되었습니다. 거버넌스 검토 결과는 이메일로 안내됩니다.</p><button class="primary-button" @click="reset">새 자산 등록</button></section>

      <form v-else-if="step===0" class="registry-card" @submit.prevent="stageSpec">
        <header><span>STEP 1 / 4</span><h2>자산 명세서 작성</h2><p>자산을 이해하고 재사용하는 데 필요한 핵심 정보를 작성합니다.</p></header>
        <div class="registry-body">
          <RegistrySection title="담당자 정보" :complete="sectionComplete.owner"><div class="registry-grid"><label><span>이름 *</span><input v-model="form.owner_name" /></label><label><span>직급 *</span><input v-model="form.owner_job_title" /></label><label><span>조직명 *</span><input v-model="form.owner_org" /></label><label><span>이메일 *</span><input v-model="form.owner_email" type="email" /></label></div></RegistrySection>
          <RegistrySection title="자산 기본 정보" :complete="sectionComplete.basic"><div class="registry-grid"><label class="full"><span>자산명 *</span><input v-model="form.asset_name" placeholder="자산의 기능과 목적이 드러나는 이름을 작성하세요." /></label><label class="full"><span>설명 *</span><textarea v-model="form.description" rows="3" placeholder="해결하는 문제와 핵심 기능을 2-3문장으로 설명하세요."></textarea></label><label><span>업무 영역 *</span><select v-model="form.business_area"><option value="">선택</option><option v-for="item in businessAreas" :key="item">{{ item }}</option></select></label><label><span>자산 성숙도 *</span><select v-model="form.maturity_level"><option value="">선택</option><option v-for="item in maturityLevels" :key="item">{{ item }}</option></select></label><ChipField class="full" label="Task 유형" :options="taskTypes" v-model="form.task_types" /><ChipField class="full" label="구현 방식" :options="implementationTypes" v-model="form.implementation_types" /><label class="full"><span>태그 * <small>Enter로 추가</small></span><input v-model="tagInput" @keydown.enter.prevent="addTag" @blur="addTag" placeholder="검색에 활용할 핵심 키워드를 입력하세요." /><div class="tag-list"><button v-for="tag in form.tags" :key="tag" type="button" @click="form.tags=form.tags.filter(item=>item!==tag)">#{{ tag }} <X :size="12" /></button></div></label></div></RegistrySection>
          <RegistrySection title="과제 정의" :complete="sectionComplete.definition"><div class="registry-grid"><GuideField class="full" label="문제 정의" v-model="form.problem_definition" guide="현재 업무의 반복 문제와 발생 원인을 구체적으로 작성하세요." /><GuideField class="full" label="As-Is Workflow" v-model="form.as_is_workflow" guide="현재 업무가 어떤 순서와 도구로 처리되는지 작성하세요." /><GuideField class="full" label="To-Be Workflow" v-model="form.to_be_workflow" guide="자산 적용 후 바뀌는 업무 흐름을 작성하세요." /><GuideField class="full" label="AI 개선 효과" v-model="form.ai_effect" guide="시간, 정확도, 표준화 등 기대 효과를 작성하세요." /></div></RegistrySection>
          <RegistrySection title="데이터" :complete="sectionComplete.data"><div class="data-switch"><label><input v-model="form.has_data" type="checkbox" />이 자산은 별도 데이터가 필요합니다</label><label v-if="form.has_data"><input v-model="form.has_train_validation_split" type="checkbox" />학습·검증 데이터 구분</label></div><div v-if="form.has_data" class="registry-grid"><label class="full"><span>Data 유형 *</span><select v-model="form.data_type"><option value="">선택</option><option v-for="item in dataTypes" :key="item">{{ item }}</option></select></label><GuideField class="full" label="데이터 설명" v-model="form.data_description" guide="데이터의 출처, 주요 컬럼과 활용 범위를 작성하세요." /><FilePicker v-if="!form.has_train_validation_split" class="full" label="샘플 데이터" :file="files.sample" @change="files.sample=$event" /><template v-else><FilePicker label="학습 샘플 데이터" :file="files.train" @change="files.train=$event" /><FilePicker label="검증 샘플 데이터" :file="files.validation" @change="files.validation=$event" /></template></div></RegistrySection>
          <RegistrySection title="기술 및 성능" :complete="sectionComplete.tech"><ItemEditor title="모델 / 알고리즘" :items="form.models" name-key="model_name" name-placeholder="모델 또는 알고리즘명" @add="form.models.push(newTech())" @remove="form.models.splice($event,1)" /><ItemEditor title="기술 스택" :items="form.tech_stacks" name-key="stack_name" name-placeholder="프레임워크 또는 기술명" @add="form.tech_stacks.push(newTech())" @remove="form.tech_stacks.splice($event,1)" /><MetricEditor title="Before / After 비교" :items="form.before_after_metrics" type="comparison" @add="form.before_after_metrics.push(newComparison())" @remove="form.before_after_metrics.splice($event,1)" /><MetricEditor title="성능 지표" :items="form.performance_metrics" type="kpi" @add="form.performance_metrics.push(newKpi())" @remove="form.performance_metrics.splice($event,1)" /></RegistrySection>
          <RegistrySection title="자산 활용 화면" :complete="sectionComplete.slides"><p class="section-guide">실제 업무에서 어떻게 활용되는지 보여주는 이미지를 업로드하세요. 탐색 화면의 자산 활용 탭에 순서대로 표시됩니다.</p><div class="slide-list"><article v-for="(slide,index) in slides" :key="slide.id"><div class="slide-preview" @click="pickSlide(index)"><img v-if="slide.preview" :src="slide.preview" alt="" /><ImagePlus v-else :size="25" /><span>{{ String(index+1).padStart(2,'0') }}</span></div><div><input v-model="slide.caption" placeholder="화면 제목" /><textarea v-model="slide.description" rows="2" placeholder="이 화면에서 확인할 수 있는 내용을 작성하세요."></textarea></div><button type="button" :disabled="slides.length===1" @click="removeSlide(index)"><X :size="16" /></button></article><button type="button" class="add-slide" @click="slides.push(newSlide())"><Plus :size="18" />이미지 추가</button></div><input ref="slideInput" type="file" accept="image/*" hidden @change="setSlideFile" /></RegistrySection>
          <p v-if="error" class="form-error page-error">{{ error }}</p><div class="registry-actions"><span v-if="!specReady"><AlertCircle :size="15" />완료되지 않은 대분류를 확인하세요.</span><button class="primary-button" :disabled="!specReady||saving">{{ saving?'저장 중...':'다음' }}<ArrowRight :size="16" /></button></div>
        </div>
      </form>

      <section v-else-if="step===1" class="registry-card compact-step"><header><span>STEP 2 / 4</span><h2>자산 연동</h2><p>Git 저장소를 연결해 실제 코드 구조를 확인합니다.</p></header><div class="registry-body"><div class="repo-connect"><label><span>Git 저장소 URL *</span><input v-model="form.repo_url" placeholder="https://github.com/organization/repository.git" /></label><label><span>브랜치</span><input v-model="form.repo_branch" placeholder="main" /></label><button class="primary-button" :disabled="cloning||!form.repo_url" @click="cloneRepo"><GitBranch :size="16" />{{ cloning?'연결 중...':'저장소 연결' }}</button></div><p v-if="repoError" class="form-error page-error">{{ repoError }}</p><RepoTree v-if="repoTree.length" :items="repoTree" /><div v-else class="content-state empty"><FolderGit2 :size="28" /><strong>연결된 저장소가 없습니다.</strong><span>Git URL과 브랜치를 입력한 뒤 저장소를 연결하세요.</span></div><div class="registry-actions"><button class="secondary-button" @click="step=0">이전</button><button class="primary-button" :disabled="!repoTree.length" @click="advance(2)">다음<ArrowRight :size="16" /></button></div></div></section>

      <section v-else-if="step===2" class="registry-card compact-step"><header><span>STEP 3 / 4</span><h2>확산 패키지 생성</h2><p>저장소를 분석해 다른 사용자가 자산을 확산할 수 있는 Claude Skill을 생성합니다.</p></header><div class="registry-body"><div v-if="!skillPlan" class="skill-start"><Wand2 :size="30" /><h3>AI가 재사용 가능한 Skill 후보를 찾습니다</h3><p>명세서와 저장소 구조를 함께 분석하므로 작업에 다소 시간이 걸릴 수 있습니다.</p><button class="primary-button" :disabled="planning" @click="planSkills"><LoaderCircle v-if="planning" class="spin" :size="16" /><Wand2 v-else :size="16" />{{ planning?'Planning 중...':'Skill 자동 생성' }}</button></div><template v-else-if="!generatedFiles.length"><div class="skill-candidates"><header><div><span>SKILL PLANNING</span><h3>생성할 Skill을 선택하세요</h3><p>{{ skillPlan.asset_summary }}</p></div></header><label v-for="candidate in skillPlan.candidates" :key="candidate.slug" :class="{selected:selectedSkills.includes(candidate.slug)}"><input v-model="selectedSkills" type="checkbox" :value="candidate.slug" /><div><span>{{ candidate.skill_type||'guide' }}</span><strong>{{ candidate.title }}</strong><p>{{ candidate.reusable_pattern }}</p><small>{{ candidate.reason }}</small></div><b>{{ candidate.diffusion_score }}</b></label><button class="primary-button" :disabled="!selectedSkills.length||generating" @click="generateSkills">선택 완료</button></div><div v-if="generating" class="skill-progress"><LoaderCircle class="spin" :size="24" /><div><strong>{{ generationLabel }}</strong><p>AI가 파일을 분석하고 생성하고 있습니다. 작업에 다소 시간이 걸릴 수 있습니다.</p></div></div></template><div v-else class="generated-skills"><header><div><span>GENERATED FILES</span><h3>생성된 파일 · {{ generatedFiles.length }} files</h3></div></header><div><SkillTree :files="generatedFiles" v-model="selectedFile" /><pre>{{ selectedFileContent }}</pre></div></div><p v-if="skillError" class="form-error page-error">{{ skillError }}</p><div class="registry-actions"><button class="secondary-button" @click="step=1">이전</button><button class="primary-button" :disabled="!generatedFiles.length" @click="advance(3)">다음<ArrowRight :size="16" /></button></div></div></section>

      <section v-else class="registry-card compact-step"><header><span>STEP 4 / 4</span><h2>최종 제출 및 승인</h2><p>등록 내용을 확인하고 필독 사항에 동의한 뒤 제출합니다.</p></header><div class="registry-body"><div class="submit-summary"><span><Bot :size="22" /></span><div><strong>{{ form.asset_name }}</strong><p>{{ form.business_area }} · {{ form.maturity_level }} · Skill {{ generatedFiles.length }} files</p></div></div><div class="agreements"><label v-for="(label,key) in agreementLabels" :key="key"><input v-model="agreements[key]" type="checkbox" /><span><Check :size="15" /></span>{{ label }}</label></div><p class="review-guide"><Clock3 :size="17" /><span><strong>승인까지 약 7일이 소요됩니다</strong>제출된 자산은 보안·라이선스·품질 검토 후 카탈로그에 공개되며 결과는 이메일로 안내됩니다.</span></p><p v-if="error" class="form-error page-error">{{ error }}</p><div class="registry-actions"><button class="secondary-button" @click="step=2">이전</button><button class="primary-button" :disabled="!allAgreed||saving" @click="submitAsset"><Send :size="16" />{{ saving?'제출 중...':'제출' }}</button></div></div></section>

      <BaseModal v-if="documentHtml" title="AI 자산 등록서" size="large" @close="documentHtml='' "><iframe class="asset-document-frame" :srcdoc="documentHtml" title="AI 자산 등록서"></iframe></BaseModal>
      <BaseModal v-if="feedback" title="자산 심사평" size="small" @close="feedback=null"><div class="feedback-modal"><span :class="feedback.approval_status"><MessageSquareText :size="22" /></span><h2>심사평</h2><dl><div><dt>심사일</dt><dd>{{ date(feedback.reviewed_at) }}</dd></div><div><dt>심사평</dt><dd>{{ feedback.review_comment||'등록된 심사평이 없습니다.' }}</dd></div></dl><button class="primary-button" @click="feedback=null">확인</button></div></BaseModal>
    </div>
  </AppLayout>
</template>

<script setup>
import { computed,onBeforeUnmount,onMounted,reactive,ref } from "vue";import { AlertCircle,ArrowRight,Bot,Check,CheckCircle2,Clock3,Eye,FolderGit2,GitBranch,ImagePlus,LoaderCircle,MessageSquareText,Plus,Send,ShieldCheck,Wand2,X } from "lucide-vue-next";import AppLayout from "../layouts/AppLayout.vue";import BaseModal from "../components/BaseModal.vue";import RegistrySection from "../components/RegistrySection.vue";import ChipField from "../components/ChipField.vue";import GuideField from "../components/GuideField.vue";import FilePicker from "../components/FilePicker.vue";import ItemEditor from "../components/ItemEditor.vue";import MetricEditor from "../components/MetricEditor.vue";import RepoTree from "../components/RepoTree.vue";import SkillTree from "../components/SkillTree.vue";import { useAuthStore } from "../stores/auth";import { apiFetch,readApiError } from "../api/client";
const auth=useAuthStore();const steps=[{title:"자산 명세서 작성",short:"핵심 정보 작성"},{title:"자산 연동",short:"Git 저장소 연결"},{title:"확산 패키지 생성",short:"Claude Skill 생성"},{title:"최종 제출 및 승인",short:"검토 요청 제출"}];const businessAreas=["생산·제조","품질","R&D·설계","SCM·구매·물류","영업·마케팅","경영지원","안전·환경·보건","IT·DX","공통"],maturityLevels=["아이디어","PoC","Pilot","운영"],taskTypes=["예측","탐지","분류","검색","질의응답","요약","생성","추출","추천","분석","최적화","자동화"],implementationTypes=["ML","DL","Computer Vision","LLM","RAG","Agent","Rule-Based","Hybrid"],dataTypes=["테이블·정형데이터","시계열 데이터","센서·IoT 데이터","문서·텍스트","이미지","영상","음성","로그","CAD·도면","코드","웹·외부 데이터","복합 데이터"];
const newTech=()=>({model_name:"",stack_name:"",description:"",reference_url:""}),newComparison=()=>({metric_name:"",before_value:"",after_value:"",improvement_rate:""}),newKpi=()=>({metric_name:"",value:"",description:""}),newSlide=()=>({id:crypto.randomUUID(),file:null,preview:"",caption:"",description:""});const initialForm=()=>({asset_id:crypto.randomUUID(),owner_name:auth.user?.displayed_name||"",owner_job_title:auth.user?.job_title||"",owner_org:auth.user?.org_name||"",owner_email:auth.user?.email||"",asset_name:"",description:"",business_area:"",maturity_level:"",task_types:[],implementation_types:[],tags:[],problem_definition:"",as_is_workflow:"",to_be_workflow:"",ai_effect:"",has_data:true,has_train_validation_split:false,data_type:"",data_description:"",models:[newTech()],tech_stacks:[newTech()],before_after_metrics:[newComparison()],performance_metrics:[newKpi()],repo_url:"",repo_branch:"main"});
const form=reactive(initialForm()),files=reactive({sample:null,train:null,validation:null}),slides=ref([newSlide()]),tagInput=ref(""),step=ref(0),maxStep=ref(0),saving=ref(false),error=ref(""),repoTree=ref([]),cloning=ref(false),repoError=ref(""),skillPlan=ref(null),planning=ref(false),selectedSkills=ref([]),generating=ref(false),generationLabel=ref(""),generatedFiles=ref([]),skillError=ref(""),selectedFile=ref(""),submitted=ref(false),myAssets=ref([]),historyLoading=ref(true),documentHtml=ref(""),feedback=ref(null),slideInput=ref(null),slideTarget=ref(0),agreements=reactive({share:false,factual:false,security:false});
const agreementLabels={share:"등록 자산의 사내 공유 및 재사용에 동의합니다.",factual:"등록 자산의 주요 정보가 실제 구현 내용과 사용 결과를 바탕으로 작성되었음을 확인합니다.",security:"등록 자산에 개인정보, 영업비밀, 외부 반출 제한 정보가 포함되지 않았음을 확인합니다."};
const filled=value=>String(value||"").trim().length>0,itemsComplete=(items,keys)=>items.length>0&&items.every(item=>keys.every(key=>filled(item[key])));const sectionComplete=computed(()=>({owner:[form.owner_name,form.owner_job_title,form.owner_org,form.owner_email].every(filled),basic:[form.asset_name,form.description,form.business_area,form.maturity_level].every(filled)&&form.task_types.length&&form.implementation_types.length&&form.tags.length,definition:[form.problem_definition,form.as_is_workflow,form.to_be_workflow,form.ai_effect].every(filled),data:!form.has_data||([form.data_type,form.data_description].every(filled)&&(form.has_train_validation_split?(files.train&&files.validation):files.sample)),tech:itemsComplete(form.models,["model_name","description"])&&itemsComplete(form.tech_stacks,["stack_name","description"])&&itemsComplete(form.before_after_metrics,["metric_name","before_value","after_value","improvement_rate"])&&itemsComplete(form.performance_metrics,["metric_name","value","description"]),slides:slides.value.length>0&&slides.value.every(item=>item.file&&filled(item.caption)&&filled(item.description))}));const specReady=computed(()=>Object.values(sectionComplete.value).every(Boolean)),allAgreed=computed(()=>Object.values(agreements).every(Boolean)),selectedFileContent=computed(()=>generatedFiles.value.find(item=>item.path===selectedFile.value)?.content||"");
const addTag=()=>{const value=tagInput.value.trim().replace(/^#/,"");if(value&&!form.tags.includes(value))form.tags.push(value);tagInput.value="";};function pickSlide(index){slideTarget.value=index;slideInput.value?.click();}function setSlideFile(event){const file=event.target.files?.[0];if(!file)return;const slide=slides.value[slideTarget.value];if(slide.preview)URL.revokeObjectURL(slide.preview);slide.file=file;slide.preview=URL.createObjectURL(file);event.target.value="";}function removeSlide(index){if(slides.value[index].preview)URL.revokeObjectURL(slides.value[index].preview);slides.value.splice(index,1);}
function payload(){return {...form,slides:slides.value.map(item=>({caption:item.caption,description:item.description})),skill_files:generatedFiles.value};}function buildData(){const data=new FormData();data.append("payload_json",JSON.stringify(payload()));slides.value.forEach(item=>item.file&&data.append("slides",item.file));if(form.has_data){if(form.has_train_validation_split){if(files.train)data.append("train_files",files.train);if(files.validation)data.append("validation_files",files.validation);}else if(files.sample)data.append("sample_files",files.sample);}return data;}async function call(path,options={},fallback){const response=await apiFetch(path,options);if(!response.ok)throw await readApiError(response,fallback);return response.status===204?null:response.json();}
async function stageSpec(){if(!specReady.value)return;saving.value=true;error.value="";try{const result=await call("/api/assets/staging",{method:"POST",body:buildData()},"자산 명세서를 임시 저장하지 못했습니다.");form.asset_id=result.asset_id;advance(1);}catch(e){error.value=e.message;}finally{saving.value=false;}}const advance=value=>{maxStep.value=Math.max(maxStep.value,value);step.value=value;window.scrollTo({top:0,behavior:"smooth"});};
async function cloneRepo(){cloning.value=true;repoError.value="";try{const result=await call("/api/assets/repository/clone",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({asset_id:form.asset_id,repo_url:form.repo_url,repo_branch:form.repo_branch||null})},"저장소를 연결하지 못했습니다.");repoTree.value=result.tree||[];}catch(e){repoError.value=e.message;}finally{cloning.value=false;}}
async function planSkills(){planning.value=true;skillError.value="";try{skillPlan.value=await call(`/api/assets/${form.asset_id}/skill-plan`,{method:"POST"},"Skill 후보를 생성하지 못했습니다.");selectedSkills.value=skillPlan.value.selected_skill_slugs||skillPlan.value.candidates.filter(item=>item.recommended).map(item=>item.slug);}catch(e){skillError.value=e.message;}finally{planning.value=false;}}
async function generateSkills(){generating.value=true;skillError.value="";try{const response=await apiFetch(`/api/assets/${form.asset_id}/skills/generate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({selected_skill_slugs:selectedSkills.value})});if(!response.ok)throw await readApiError(response,"Skill을 생성하지 못했습니다.");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==="step_started")generationLabel.value=event.label;if(event.type==="error")throw new Error(event.message);if(event.type==="completed"){generatedFiles.value=event.files||[];selectedFile.value=generatedFiles.value[0]?.path||"";}}if(done)break;}}catch(e){skillError.value=e.message;}finally{generating.value=false;}}
async function submitAsset(){saving.value=true;error.value="";try{await call("/api/assets",{method:"POST",body:buildData()},"자산을 제출하지 못했습니다.");submitted.value=true;await loadMine();}catch(e){error.value=e.message;}finally{saving.value=false;}}async function loadMine(){historyLoading.value=true;try{myAssets.value=await call("/api/assets/mine",{},"등록 기록을 불러오지 못했습니다.");}catch(e){error.value=e.message;}finally{historyLoading.value=false;}}async function viewDocument(asset){try{const response=await apiFetch(`/api/assets/${asset.asset_id}/registration-document`);if(!response.ok)throw await readApiError(response,"등록서를 불러오지 못했습니다.");documentHtml.value=await response.text();}catch(e){error.value=e.message;}}
const statusLabel=value=>({submitted:"제출 완료",approved:"승인",rejected:"반려"}[value]||value),date=value=>String(value||"").slice(0,10);function reset(){slides.value.forEach(item=>item.preview&&URL.revokeObjectURL(item.preview));Object.assign(form,initialForm());Object.assign(files,{sample:null,train:null,validation:null});slides.value=[newSlide()];step.value=0;maxStep.value=0;repoTree.value=[];skillPlan.value=null;generatedFiles.value=[];selectedSkills.value=[];Object.keys(agreements).forEach(key=>agreements[key]=false);submitted.value=false;}
onMounted(loadMine);onBeforeUnmount(()=>slides.value.forEach(item=>item.preview&&URL.revokeObjectURL(item.preview)));
</script>
