import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import "./styles/tokens.css";
import "./styles.css";
import "./styles/community.css";
import "./styles/forms.css";
import "./styles/idea-process.css";
import "./styles/idea-popup.css";
import "./styles/news-popup.css";
import "./styles/studio.css";
import "./styles/dx-discovery.css";
import "./styles/asset-recommendation.css";
import "./styles/asset-catalog.css";
import "./styles/asset-qa.css";
import "./styles/asset-detail.css";
import "./styles/registry.css";

createApp(App).use(createPinia()).use(router).mount("#app");
