<template>
  <section class="asset-qa">
    <header><div><span>ASSET Q&amp;A</span><h3>자산에 대해 묻고 답하기</h3><p>적용 방법과 기술적인 궁금증을 자산 담당자 및 동료와 나눕니다.</p></div></header>
    <form class="qa-question-form" @submit.prevent="createQuestion"><select v-model="topic"><option>적용 문의</option><option>기술 문의</option><option>데이터 문의</option><option>개선 제안</option></select><textarea v-model="question" rows="3" placeholder="자산 활용에 대해 궁금한 점을 구체적으로 작성해 주세요."></textarea><button class="primary-button" :disabled="!question.trim()">질문 등록</button></form>
    <p v-if="error" class="form-error">{{ error }}</p>
    <div v-if="loading" class="content-state"><LoaderCircle class="spin" />Q&amp;A를 불러오는 중입니다.</div>
    <div v-else-if="threads.length" class="qa-list"><article v-for="thread in threads" :key="thread.qa_post_id"><header><span>{{ thread.topic }}</span><div><strong>{{ thread.writer_name }} {{ thread.writer_job_title }}</strong><small>{{ thread.writer_org }} · {{ date(thread.created_at) }}</small></div><em v-if="thread.is_owner">자산 담당자</em></header><template v-if="editingId===thread.qa_post_id"><textarea v-model="editText" rows="3"></textarea><div class="qa-edit-actions"><button @click="cancelEdit">취소</button><button @click="saveEdit(thread.qa_post_id)">저장</button></div></template><p v-else>{{ thread.content }}</p><div class="qa-actions"><button :class="{active:thread.helpful_by_me}" @click="toggleHelpful(thread)"><ThumbsUp :size="13" />도움돼요 {{ thread.helpful_count }}</button><button @click="replyTarget=replyTarget===thread.qa_post_id?'':thread.qa_post_id"><MessageCircle :size="13" />답글 {{ thread.replies.length }}</button><button v-if="thread.can_edit" @click="startEdit(thread)">수정</button><button v-if="thread.can_edit" @click="remove(thread.qa_post_id)">삭제</button></div><div v-if="thread.replies.length" class="qa-replies"><article v-for="reply in thread.replies" :key="reply.qa_post_id"><header><CornerDownRight :size="14" /><div><strong>{{ reply.writer_name }} {{ reply.writer_job_title }}</strong><small>{{ reply.writer_org }} · {{ date(reply.created_at) }}</small></div><em v-if="reply.is_owner">자산 담당자</em></header><template v-if="editingId===reply.qa_post_id"><textarea v-model="editText" rows="2"></textarea><div class="qa-edit-actions"><button @click="cancelEdit">취소</button><button @click="saveEdit(reply.qa_post_id)">저장</button></div></template><p v-else>{{ reply.content }}</p><div v-if="reply.can_edit" class="qa-actions"><button @click="startEdit(reply)">수정</button><button @click="remove(reply.qa_post_id)">삭제</button></div></article></div><form v-if="replyTarget===thread.qa_post_id" class="qa-reply-form" @submit.prevent="createReply(thread.qa_post_id)"><textarea v-model="replyText" rows="2" placeholder="답글을 작성해 주세요."></textarea><button class="primary-button" :disabled="!replyText.trim()">답글 등록</button></form></article></div>
    <div v-else class="content-state empty"><MessageCircle :size="28" /><strong>등록된 질문이 없습니다.</strong><span>자산 활용에 대한 첫 질문을 남겨보세요.</span></div>
  </section>
</template>
<script setup>
import { onMounted,ref } from "vue";import { CornerDownRight,LoaderCircle,MessageCircle,ThumbsUp } from "lucide-vue-next";import { apiFetch,readApiError } from "../api/client";
const props=defineProps({assetId:{type:String,required:true}});const threads=ref([]),loading=ref(true),error=ref(""),topic=ref("적용 문의"),question=ref(""),replyTarget=ref(""),replyText=ref(""),editingId=ref(""),editText=ref("");const date=value=>String(value||"").slice(0,10);
async function call(path,options={},fallback){const response=await apiFetch(path,options);if(!response.ok)throw await readApiError(response,fallback);return response.status===204?null:response.json();}async function load(){loading.value=true;error.value="";try{threads.value=await call(`/api/assets/catalog/${props.assetId}/qa`,{},"Q&A를 불러오지 못했습니다.");}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function createQuestion(){try{await call(`/api/assets/catalog/${props.assetId}/qa/questions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic:topic.value,content:question.value.trim()})},"질문을 등록하지 못했습니다.");question.value="";await load();}catch(e){error.value=e.message;}}
async function createReply(id){try{await call(`/api/assets/catalog/${props.assetId}/qa/questions/${id}/replies`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:replyText.value.trim()})},"답글을 등록하지 못했습니다.");replyText.value="";replyTarget.value="";await load();}catch(e){error.value=e.message;}}
const startEdit=item=>{editingId.value=item.qa_post_id;editText.value=item.content;};const cancelEdit=()=>{editingId.value="";editText.value="";};async function saveEdit(id){try{await call(`/api/assets/catalog/${props.assetId}/qa/posts/${id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:editText.value.trim()})},"내용을 수정하지 못했습니다.");cancelEdit();await load();}catch(e){error.value=e.message;}}
async function remove(id){if(!confirm("작성한 내용을 삭제할까요? 답글이 있는 질문은 답글도 함께 삭제됩니다."))return;try{await call(`/api/assets/catalog/${props.assetId}/qa/posts/${id}`,{method:"DELETE"},"내용을 삭제하지 못했습니다.");await load();}catch(e){error.value=e.message;}}
async function toggleHelpful(thread){try{const method=thread.helpful_by_me?"DELETE":"POST";const result=await call(`/api/assets/catalog/${props.assetId}/qa/questions/${thread.qa_post_id}/helpful`,{method},"도움돼요를 반영하지 못했습니다.");thread.helpful_count=result.helpful_count;thread.helpful_by_me=result.helpful_by_me;}catch(e){error.value=e.message;}}onMounted(load);
</script>
