<template>
  <Teleport to="body">
    <button class="asset-drawer-backdrop" aria-label="상세 닫기" @click="$emit('close')"></button>
    <aside class="asset-drawer">
      <div v-if="loading" class="content-state modal-loading"><LoaderCircle class="spin" :size="28" />자산 정보를 불러오는 중입니다.</div>
      <template v-else-if="asset">
        <header class="asset-drawer-head"><button aria-label="닫기" @click="$emit('close')"><X :size="19" /></button><span>{{ asset.business_area }}</span><h2>{{ asset.asset_name }}</h2><p>{{ asset.description }}</p><div class="asset-owner"><i><UserRound :size="16" /></i><div><strong>{{ asset.owner_name||'자산 담당자' }} <em>{{ asset.owner_job_title }}</em></strong><span>{{ asset.owner_org }}</span><button v-if="asset.owner_email" @click="copy(asset.owner_email)"><Mail :size="11" />{{ asset.owner_email }}</button></div></div><dl><div><dt>{{ asset.maturity_level }}</dt><dd>자산 성숙도</dd></div><div><dt>{{ number(asset.view_count) }}</dt><dd>조회 수</dd></div><div><dt>{{ number(asset.diffusion_attempt_count) }}</dt><dd>확산 시도</dd></div><div><dt>{{ number(asset.diffusion_completed_count) }}</dt><dd>확산 완료</dd></div><div><dt>{{ date(asset.updated_at) }}</dt><dd>업데이트</dd></div></dl></header>
        <nav class="asset-drawer-tabs"><button v-for="item in tabs" :key="item.key" :class="{active:tab===item.key}" @click="selectTab(item.key)">{{ item.label }}</button></nav>
        <div class="asset-drawer-body">
          <div v-if="tab==='overview'" class="asset-definition"><section><header><span>01</span><b>문제 정의</b></header><p>{{ asset.problem_definition }}</p></section><div><section><header><span>02</span><b>As-Is Workflow</b></header><p>{{ asset.as_is_workflow }}</p></section><ArrowRight :size="20" /><section><header><span>03</span><b>To-Be Workflow</b></header><p>{{ asset.to_be_workflow }}</p></section></div><section class="effect"><header><span>04</span><b>AI 개선 효과</b></header><p>{{ asset.ai_effect }}</p></section></div>
          <div v-else-if="tab==='tech'" class="asset-tech"><section><h3>모델 / 알고리즘</h3><article v-for="(item,index) in asset.models" :key="index"><b>{{ item.model_name||item.name }}</b><p>{{ item.description }}</p><a v-if="item.reference_url" :href="item.reference_url" target="_blank">참조 링크 <ExternalLink :size="12" /></a></article><p v-if="!asset.models?.length">등록된 모델 정보가 없습니다.</p></section><section><h3>기술 스택</h3><article v-for="(item,index) in asset.tech_stacks" :key="index"><b>{{ item.stack_name||item.name }}</b><p>{{ item.description }}</p><a v-if="item.reference_url" :href="item.reference_url" target="_blank">참조 링크 <ExternalLink :size="12" /></a></article><p v-if="!asset.tech_stacks?.length">등록된 기술 스택 정보가 없습니다.</p></section></div>
          <div v-else-if="tab==='data'" class="asset-data"><section><h3>데이터 설명</h3><p>{{ asset.has_data?(asset.data_description||'등록된 데이터 설명이 없습니다.'):'별도 데이터 첨부 없이 활용할 수 있는 자산입니다.' }}</p><span v-if="asset.data_type">{{ asset.data_type }}</span></section><section v-if="asset.has_data"><h3>샘플 데이터</h3><article v-for="file in asset.data_files" :key="file.data_file_id"><Database :size="19" /><div><b>{{ file.file_name }}</b><span>{{ role(file.data_role) }} · {{ fileSize(file.file_size) }}</span></div><button @click="download(file.download_url,file.file_name)"><Download :size="14" />Download</button></article><p v-if="!asset.data_files?.length">첨부된 샘플 데이터가 없습니다.</p></section></div>
          <div v-else-if="tab==='performance'" class="asset-performance"><section><header><div><span>WORKFLOW IMPACT</span><h3>Before / After 비교</h3></div></header><article v-for="(item,index) in asset.before_after_metrics" :key="index"><div><span>0{{ index+1 }}</span><b>{{ item.metric_name }}</b><em>{{ item.improvement_rate }}</em></div><div><small>BEFORE</small><strong>{{ item.before_value }}</strong><ArrowRight :size="17" /><small>AFTER</small><strong>{{ item.after_value }}</strong></div></article><p v-if="!asset.before_after_metrics?.length">등록된 비교 지표가 없습니다.</p></section><section><header><div><span>PERFORMANCE KPI</span><h3>성능 지표</h3></div></header><article v-for="(item,index) in asset.performance_metrics" :key="index" class="kpi"><CheckCircle2 :size="18" /><div><b>{{ item.metric_name }}</b><p>{{ item.description }}</p></div><strong>{{ item.value }}</strong></article><p v-if="!asset.performance_metrics?.length">등록된 성능 지표가 없습니다.</p></section></div>
          <div v-else-if="tab==='demo'" class="asset-demo"><template v-if="currentSlide"><button class="asset-demo-image" @click="lightbox=true"><img :src="apiUrl(currentSlide.url)" :alt="currentSlide.caption||asset.asset_name" /><Maximize2 :size="17" /></button><div><span>{{ slideIndex+1 }} / {{ asset.slides.length }}</span><section><b>{{ currentSlide.caption||'자산 활용 화면' }}</b><p>{{ currentSlide.description }}</p></section><nav><button :disabled="slideIndex===0" @click="slideIndex--"><ChevronLeft /></button><button :disabled="slideIndex>=asset.slides.length-1" @click="slideIndex++"><ChevronRight /></button></nav></div></template><p v-else class="asset-empty">등록된 자산 활용 화면이 없습니다.</p></div>
          <div v-else-if="tab==='diffusion'" class="asset-guide"><section><span>GIT REPOSITORY</span><h3>저장소에서 시작하기</h3><p>등록된 구현 코드를 확인하고 업무 환경에 맞게 적용합니다.</p><div><code>{{ asset.repo_url||'등록된 Git 저장소가 없습니다.' }}</code><button v-if="asset.repo_url" @click="copyRepo">{{ copied?'Copied':'Copy' }}</button></div></section><section><span>CLAUDE SKILL</span><h3>확산 패키지 활용</h3><p>Claude가 프로젝트 구조와 재사용 가능한 실행 방식을 이해하도록 구성된 Skill 패키지입니다.</p><button class="primary-button" :disabled="!asset.skill_download_url" @click="download(asset.skill_download_url,`${asset.asset_name}-skills.zip`)"><Download :size="15" />Skill 다운로드</button></section></div>
          <DiffusionCases v-else-if="tab==='cases'" :asset="asset" @count-change="$emit('count-change',$event)" />
          <AssetQa v-else-if="tab==='qa'" :asset-id="asset.asset_id" />
        </div>
      </template>
      <div v-else class="content-state modal-loading">{{ error||'자산 정보를 불러오지 못했습니다.' }}</div>
    </aside>
    <div v-if="lightbox&&currentSlide" class="asset-lightbox" @click="lightbox=false"><section @click.stop><button @click="lightbox=false"><X /></button><img :src="apiUrl(currentSlide.url)" :alt="currentSlide.caption" /><p>{{ currentSlide.description }}</p></section></div>
  </Teleport>
</template>

<script setup>
import { computed, ref } from "vue";import { ArrowRight,CheckCircle2,ChevronLeft,ChevronRight,Database,Download,ExternalLink,LoaderCircle,Mail,Maximize2,UserRound,X } from "lucide-vue-next";
import { apiFetch, readApiError, resolveApiUrl } from "../api/client";import DiffusionCases from "./DiffusionCases.vue";import AssetQa from "./AssetQa.vue";
const props=defineProps({asset:Object,loading:Boolean,error:String});defineEmits(["close","count-change"]);const tab=ref("overview"),slideIndex=ref(0),lightbox=ref(false),copied=ref(false);
const tabs=[{key:"overview",label:"과제 설명"},{key:"tech",label:"적용 기술"},{key:"data",label:"데이터"},{key:"performance",label:"성능 지표"},{key:"demo",label:"자산 활용"},{key:"diffusion",label:"확산 가이드"},{key:"cases",label:"확산 사례"},{key:"qa",label:"Q&A"}];
const currentSlide=computed(()=>props.asset?.slides?.[slideIndex.value]);const number=value=>Number(value||0).toLocaleString(),date=value=>String(value||"").slice(0,10),role=value=>({train:"학습",validation:"검증",sample:"샘플"}[value]||value),apiUrl=resolveApiUrl;
const fileSize=value=>{const n=Number(value||0);return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;};const selectTab=value=>{tab.value=value;if(value==="demo")slideIndex.value=0;};
async function copy(value){await navigator.clipboard.writeText(value);}async function copyRepo(){await copy(props.asset.repo_url);copied.value=true;setTimeout(()=>copied.value=false,1500);}
async function download(path,name){const response=await apiFetch(path);if(!response.ok)throw await readApiError(response,"파일을 내려받지 못했습니다.");const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);}
</script>
