<template>
  <section class="diffusion-cases">
    <header><div><span>DIFFUSION CASES</span><h3>확산 사례 목록 · 총 {{ cases.length }}건</h3><p>이 자산을 실제 업무에 적용한 경험과 변경 방식을 공유합니다.</p></div><button class="primary-button" @click="openForm()"><Plus :size="15" />사례 등록</button></header>
    <div v-if="loading" class="content-state"><LoaderCircle class="spin" />사례를 불러오는 중입니다.</div>
    <div v-else-if="cases.length" class="case-list"><article v-for="item in cases" :key="item.diffusion_case_id"><header><span>{{ item.stage_label }}</span><div v-if="item.can_edit"><button @click="openForm(item)"><Pencil :size="13" />수정</button><button @click="remove(item)"><Trash2 :size="13" />삭제</button></div></header><h4>{{ item.title }}</h4><small>{{ item.writer_org }} · {{ item.writer_name }} {{ item.writer_job_title }}</small><dl><div><dt>적용 업무</dt><dd>{{ item.applied_work }}</dd></div><div><dt>수정·활용 방식</dt><dd>{{ item.customization }}</dd></div><div><dt>적용 효과</dt><dd>{{ item.effect }}</dd></div></dl><a v-if="item.git_url" :href="item.git_url" target="_blank"><GitBranch :size="14" />공유 코드 보기</a></article></div>
    <div v-else class="content-state empty"><GitBranch :size="28" /><strong>아직 등록된 확산 사례가 없습니다.</strong><span>실제 업무 적용 경험을 첫 사례로 공유해 주세요.</span></div>
    <BaseModal v-if="formOpen" :title="editingId?'확산 사례 수정':'확산 사례 등록'" size="medium" @close="formOpen=false"><form class="case-form" @submit.prevent="save"><header><span>DIFFUSION CASE</span><h2>{{ editingId?'확산 사례 수정':'확산 사례 등록' }}</h2><p><b>{{ asset.asset_name }}</b>을 실제 업무에 적용한 경험을 공유합니다.</p></header><label class="form-field"><span>사례 제목 <b>*</b></span><input v-model="form.title" placeholder="자산을 적용한 업무와 핵심 결과가 드러나도록 작성하세요." /></label><label class="form-field"><span>확산 단계 <b>*</b></span><select v-model="form.stage"><option value="">선택</option><option value="poc">PoC</option><option value="pilot">Pilot</option><option value="production">운영</option></select></label><label class="form-field"><span>적용 업무 <b>*</b></span><textarea v-model="form.applied_work" rows="3" placeholder="어떤 업무·공정·프로세스에 적용했는지 작성하세요."></textarea></label><label class="form-field"><span>수정·활용 방식 <b>*</b></span><textarea v-model="form.customization" rows="3" placeholder="업무 환경에 맞게 어떻게 수정하고 활용했는지 작성하세요."></textarea></label><label class="form-field"><span>적용 효과 <b>*</b></span><textarea v-model="form.effect" rows="3" placeholder="적용 후 확인된 정량적·정성적 효과를 작성하세요."></textarea></label><label class="form-field"><span>공유 코드 Git URL <small>선택</small></span><input v-model="form.git_url" type="url" placeholder="https://git.hyundai-wia.com/..." /></label><p v-if="error" class="form-error">{{ error }}</p><div class="form-buttons equal"><button type="button" class="secondary-button" @click="formOpen=false">취소</button><button class="primary-button" :disabled="saving">{{ saving?'저장 중...':editingId?'수정':'등록' }}</button></div></form></BaseModal>
  </section>
</template>
<script setup>
import { onMounted, reactive, ref } from "vue";import { GitBranch,LoaderCircle,Pencil,Plus,Trash2 } from "lucide-vue-next";import BaseModal from "./BaseModal.vue";import { apiFetch,readApiError } from "../api/client";
const props=defineProps({asset:{type:Object,required:true}}),emit=defineEmits(["count-change"]);const cases=ref([]),loading=ref(true),formOpen=ref(false),editingId=ref(""),saving=ref(false),error=ref("");const form=reactive({title:"",stage:"",applied_work:"",customization:"",effect:"",git_url:""});
async function call(path,options={},fallback){const response=await apiFetch(path,options);if(!response.ok)throw await readApiError(response,fallback);return response.status===204?null:response.json();}async function load(){loading.value=true;try{cases.value=await call(`/api/assets/catalog/${props.asset.asset_id}/diffusion-cases`,{},"사례를 불러오지 못했습니다.");}finally{loading.value=false;}}
function openForm(item){editingId.value=item?.diffusion_case_id||"";Object.assign(form,{title:item?.title||"",stage:item?.stage||"",applied_work:item?.applied_work||"",customization:item?.customization||"",effect:item?.effect||"",git_url:item?.git_url||""});error.value="";formOpen.value=true;}
async function save(){if(!form.title||!form.stage||!form.applied_work||!form.customization||!form.effect){error.value="필수 항목을 모두 작성하세요.";return;}saving.value=true;try{const path=`/api/assets/catalog/${props.asset.asset_id}/diffusion-cases${editingId.value?`/${editingId.value}`:""}`;const result=await call(path,{method:editingId.value?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)},"사례를 저장하지 못했습니다.");emit("count-change",result.diffusion_completed_count);formOpen.value=false;await load();}catch(e){error.value=e.message;}finally{saving.value=false;}}
async function remove(item){if(!confirm("이 확산 사례를 삭제할까요?"))return;try{const result=await call(`/api/assets/catalog/${props.asset.asset_id}/diffusion-cases/${item.diffusion_case_id}`,{method:"DELETE"},"사례를 삭제하지 못했습니다.");emit("count-change",result.diffusion_completed_count);await load();}catch(e){error.value=e.message;}}onMounted(load);
</script>
